version: 4.0.2.{build}

image: Visual Studio 2017

install:
  - ps: .\scripts\updateversion.ps1
  - ps: .\scripts\installandruneventstore.ps1

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

configuration: Release

before_build:
  - msbuild /t:restore EventStore.ClientAPI.NetCore.sln

build:
  project: EventStore.ClientAPI.NetCore.sln
  publish_nuget: true
  verbosity: minimal

test_script:  
  - dotnet test test\EventStore.ClientAPI.NetCore.Tests\EventStore.ClientAPI.NetCore.Tests.csproj --no-build


# deploy:
#   provider: NuGet
#   on:
#     appveyor_repo_tag: true
#   api_key: 
#     secure: 
#   artifact: /.*\.nupkg/
